include         /etc/openldap/schema/core.schema
include         /etc/openldap/schema/cosine.schema
include         /etc/openldap/schema/inetorgperson.schema
include         /etc/openldap/schema/nis.schema

pidfile         /var/run/slapd.pid
argsfile        /var/run/slapd.args

access to *
    by dn.exact="gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth" manage
    by * break

access to attrs=userPassword,shadowLastChange
    by self write
    by dn="cn=admin,dc=amyinfo,dc=com" write
    by anonymous auth
    by * none

access to *
    by self read
    by dn="cn=admin,dc=amyinfo,dc=com" write
    by * none

database        mdb
maxsize         8388608
suffix          "dc=amyinfo,dc=com"
rootdn          "cn=admin,dc=amyinfo,dc=com"
rootpw          {SSHA}CHANGE_THIS_TO_YOUR_HASH
directory       /var/lib/openldap
index           objectClass eq
index           uid eq
index           memberUid eq
